export const COLOR_OBJ = {
  black: '#000',
  white: '#FFF',
  red: '#E22C35',
  green: '#75A201',
  yellow: '#FEE44D',
  lightBlue: '#4379AB',
  lightGray: '#ABABAB',
  colorLight: '#445F7E',
  colorDark: '#5B799B',
  colorMainPrimary: '#445F7E',
  colorContrastTextPrimary: '#FFF',
  colorMainSecondary: '#5B799B',
  colorContrastTextSecondary: '#212121',
}

export const DARK_COLOR = {
  text: '#FFF',
  color: COLOR_OBJ.colorDark,
  largeHeading: COLOR_OBJ.colorDark,
  pageHeading: COLOR_OBJ.colorDark,
  subHeading: '#FFF',
  background: 'radial-gradient(rgba(83,83,83,1) 0%, rgba(56,56,56,1) 64.82%, rgba(92,92,92,1) 100%)',
  mediaBackground: '#5C5C5C',
  mediaTextBackground: '#748BA5',
  mediaCardHeading: '#FFF',
  mediaCardSubheading: '#E3E3E3',
  mediaFilterButton: '#5B799B',
  buttonPrimary: '#5B799B',
  buttonSecondary: '#4379AB',
  textFieldBackground: '#748BA5',
  textFieldText: '#FFF',
  menuText: COLOR_OBJ.colorDark,
  menuIcon: COLOR_OBJ.colorDark
}

export const LIGHT_COLOR = {
  text: '#333',
  color: COLOR_OBJ.colorLight,
  largeHeading: COLOR_OBJ.colorLight,
  pageHeading: COLOR_OBJ.colorLight,
  subHeading: '#333',
  background: 'radial-gradient(rgba(255,255,255,1) 0%, rgba(244,244,244,1) 65.52%, rgba(178,177,177,0.22) 100%)',
  mediaBackground: '#FFF',
  mediaTextBackground: '#FFF',
  mediaCardHeading: COLOR_OBJ.colorLight,
  mediaCardSubheading: '#748BA5',
  mediaFilterButton: COLOR_OBJ.colorLight,
  buttonPrimary: '#445F7E',
  buttonSecondary: '#445F7E',
  textFieldBackground: '#748BA5',
  textFieldText: '#FFF',
  menuText: COLOR_OBJ.colorLight,
  menuIcon: COLOR_OBJ.colorLight
}